eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://172.31.32.114:8761/eureka/
        instance:
          hostname: localhost
